let body=document.getElementById("body")
body.style.margin="0%"
body.style.padding="0%"
let navbar=document.getElementById("navbar")
navbar.style.listStyle="none"
navbar.style.display="flex"
navbar.style.justifyContent="space-around"
// navbar.style.border="1px solid black"
navbar.style.width="100%"
navbar.style.height="70px"
navbar.style.alignItems="center"
navbar.style.fontFamily="monospace"
// navbar.style.fontWeight="bold"
navbar.style.backgroundColor="white"
navbar.style.boxShadow=" 10px 10px 20px grey" ;
// navbar.style.position="fixed"


let center =document.getElementById("center")
center.style.display="flex"
center.style.gap="50px"
center.style.textTransform="capitalize"
center.style.fontSize="25px"
let right =document.getElementById("right")
right.style.display="flex"
right.style.gap="30px"
right.style.fontSize="30px"

let container=document.getElementById("container")
// container.style.border="1px solid black"
container.style.height="150px"
container.style.fontSize="50px"
container.style.display="flex"
container.style.justifyContent="center"
container.style.alignItems="center"
container.style.textTransform="capitalize"
container.style.fontWeight="bold"
container.style.color="rgb(34, 25, 119)"
container.style.fontFamily="monospace"
container.style.textShadow=" 10px 10px 10px grey" 
let icon=document.getElementById("icon")
icon.style.color="rgba(245, 6, 153, 0.91)"


let container1=document.getElementById("container1")
// container1.style.border="1px solid black"
container1.style.height="50px"
container1.style.listStyle="none"
container1.style.display="flex"
container1.style.justifyContent="center"
container1.style.alignItems="center"
container1.style.textAlign="center"
container1.style.gap="70px"
container1.style.textTransform="capitalize"
container1.style.fontSize="30px"
container1.style.fontWeight="bold"
container1.style.marginLeft="50px"
container1.style.borderBottom="2px solid grey"
container1.style.width="1200px"
let feature=document.getElementById("feature")
feature.style.color="rgb(226, 26, 136)"


let container2=document.getElementById("container2")
// container2.style.border="1px solid black"
container2.style.marginTop="50px"
container2.style.display="flex"
container2.style.gap="60px"
container2.style.flexWrap="wrap"
container2.style.justifyContent="center"
container2.style.alignItems="center"
// container2.style.width="fit-content"
let card1=document.getElementById("card1")
card1.style.padding="10px"
// card1.style.border="1px solid black"
card1.style.boxShadow=" 10px 10px 20px grey" 
card1.style.width="300px"
let description=document.getElementById("description")
description.style.textAlign="justify"
let h2=document.getElementById("h2")
h2.style.textAlign="center"
h2.style.fontSize="30px"
h2.style.textTransform="capitalize"
h2.style.color="maroon"
let content=document.getElementById("content")
content.style.textAlign="center"
content.style.fontSize="20px"
content.style.textTransform="capitalize"
content.style.color="orangered"

let card2=document.getElementById("card2")
// card2.style.border="1px solid black"
card2.style.boxShadow=" 10px 10px 20px grey" 
card2.style.padding="10px"
card2.style.width="300px"
let description1=document.getElementById("description1")
description1.style.textAlign="justify"
let h3=document.getElementById("h3")
h3.style.textAlign="center"
h3.style.fontSize="30px"
h3.style.textTransform="capitalize"
h3.style.color="maroon"
let content1=document.getElementById("content1")
content1.style.textAlign="center"
content1.style.fontSize="20px"
content1.style.textTransform="capitalize"
content1.style.color="orangered"
let card3=document.getElementById("card3")
// card3.style.border="1px solid black"
card3.style.boxShadow=" 10px 10px 20px grey" 
card3.style.padding="10px"
card3.style.width="300px"
let description2=document.getElementById("description2")
description2.style.textAlign="justify"
let h4=document.getElementById("h4")
h4.style.textAlign="center"
h4.style.fontSize="30px"
h4.style.textTransform="capitalize"
h4.style.color="maroon"
let content2=document.getElementById("content2")
content2.style.textAlign="center"
content2.style.fontSize="20px"
content2.style.textTransform="capitalize"
content2.style.color="orangered"
let card4=document.getElementById("card4")
// card4.style.border="1px solid black"
card4.style.boxShadow=" 10px 10px 20px grey" 
card4.style.padding="10px"
card4.style.width="300px"
let description3=document.getElementById("description3")
description3.style.textAlign="justify"
let h5=document.getElementById("h5")
h5.style.textAlign="center"
h5.style.fontSize="30px"
h5.style.textTransform="capitalize"
h5.style.color="maroon"
let content3=document.getElementById("content3")
content3.style.textAlign="center"
content3.style.fontSize="20px"
content3.style.textTransform="capitalize"
content3.style.color="orangered"
let card5=document.getElementById("card5")
// card5.style.border="1px solid black"
card5.style.boxShadow=" 10px 10px 20px grey" 
card5.style.padding="10px"
card5.style.width="300px"
let description4=document.getElementById("description4")
description4.style.textAlign="justify"
let h6=document.getElementById("h6")
h6.style.textAlign="center"
h6.style.fontSize="30px"
h6.style.textTransform="capitalize"
h6.style.color="maroon"
let content4=document.getElementById("content4")
content4.style.textAlign="center"
content4.style.fontSize="20px"
content4.style.textTransform="capitalize"
content4.style.color="orangered"
let card6=document.getElementById("card6")
// card6.style.border="1px solid black"
card6.style.boxShadow=" 10px 10px 20px grey" 
card6.style.padding="10px"
card6.style.width="300px"
let description5=document.getElementById("description5")
description5.style.textAlign="justify"
let h7=document.getElementById("h7")
h7.style.textAlign="center"
h7.style.fontSize="30px"
h7.style.textTransform="capitalize"
h7.style.color="maroon"
let content5=document.getElementById("content5")
content5.style.textAlign="center"
content5.style.fontSize="20px"
content5.style.textTransform="capitalize"
content5.style.color="orangered"

let footer=document.getElementById("footer")
footer.style.listStyle="none"
footer.style.display="flex"
footer.style.flexDirection="column"
// footer.style.border="1px solid black"
footer.style.backgroundColor="darkblue"
footer.style.color="white"
footer.style.gap="10px"
footer.style.justifyContent="center"
footer.style.alignItems="center"
footer.style.height="300px"
footer.style.textTransform="capitalize"
footer.style.fontSize="30px"
footer.style.marginTop="40px"
footer.style.boxShadow=" 10px 10px 20px grey" 


let ef=document.getElementById("ef")
ef.style.textTransform="uppercase"
ef.style.fontWeight="bolder"
ef.style.fontFamily="monospace"
ef.style.color="whitesmoke"
ef.style.textShadow=" 10px 10px 15px black"
let fus=document.getElementById("fus")
fus.style.borderTop="1px solid white"
fus.style.width="80%"
fus.style.paddingTop="20px"
fus.style.textAlign="center"
fus.style.fontSize="30px"
fus.style.paddingBottom="20px"


let icon1=document.getElementById("icon1")
icon1.style.color="rgb(240, 30, 159)"
icon1.style.fontSize="40px"

let icon2=document.getElementById("icon2")
icon2.style.display="flex"
icon2.style.gap="50px"
icon2.style.color="yellow"
icon2.style.fontSize="40px"